export interface LanguageOption {
  text: string
  value: string
}

export const availableLanguages: LanguageOption[] = [
  // 核心语言（高熟练度，流畅交流）
  { text: '英语 (English)', value: '英语' },
  { text: '中文 (简体/繁體)', value: '中文' },
  { text: '西班牙语 (Español)', value: '西班牙语' },
  { text: '法语 (Français)', value: '法语' },
  { text: '阿拉伯语 (العربية)', value: '阿拉伯语' },
  { text: '俄语 (Русский)', value: '俄语' },
  { text: '葡萄牙语 (Português)', value: '葡萄牙语' },
  { text: '德语 (Deutsch)', value: '德语' },
  { text: '日语 (日本語)', value: '日语' },
  { text: '韩语 (한국어)', value: '韩语' },
  { text: '印地语 (हिन्दी)', value: '印地语' },
  { text: '土耳其语 (Türkçe)', value: '土耳其语' },
  { text: '意大利语 (Italiano)', value: '意大利语' },
  { text: '荷兰语 (Nederlands)', value: '荷兰语' },
  { text: '波兰语 (Polski)', value: '波兰语' },

  // 中等熟练度
  { text: '泰语 (ไทย)', value: '泰语' },
  { text: '越南语 (Tiếng Việt)', value: '越南语' },
  { text: '印尼语 (Bahasa Indonesia)', value: '印尼语' },
  { text: '波斯语 (فارسی)', value: '波斯语' },
  { text: '乌尔都语 (اردو)', value: '乌尔都语' },
  { text: '孟加拉语 (বাংলা)', value: '孟加拉语' },
  { text: '泰米尔语 (தமிழ்)', value: '泰米尔语' },
  { text: '希伯来语 (עברית)', value: '希伯来语' },
  { text: '希腊语 (Ελληνικά)', value: '希腊语' },
  { text: '瑞典语 (Svenska)', value: '瑞典语' },
  { text: '芬兰语 (Suomi)', value: '芬兰语' },
  { text: '丹麦语 (Dansk)', value: '丹麦语' },
  { text: '挪威语 (Norsk)', value: '挪威语' },
  { text: '捷克语 (Čeština)', value: '捷克语' },
  { text: '匈牙利语 (Magyar)', value: '匈牙利语' },
  { text: '罗马尼亚语 (Română)', value: '罗马尼亚语' },
  { text: '乌克兰语 (Українська)', value: '乌克兰语' },
  { text: '保加利亚语 (Български)', value: '保加利亚语' },
  { text: '克罗地亚语 (Hrvatski)', value: '克罗地亚语' },
  { text: '塞尔维亚语 (Српски)', value: '塞尔维亚语' },

  // 基础交流
  { text: '斯瓦希里语 (Kiswahili)', value: '斯瓦希里语' },
  { text: '豪萨语 (Hausa)', value: '豪萨语' },
  { text: '约鲁巴语 (Yorùbá)', value: '约鲁巴语' },
  { text: '祖鲁语 (isiZulu)', value: '祖鲁语' },
  { text: '阿姆哈拉语 (አማርኛ)', value: '阿姆哈拉语' },
  { text: '缅甸语 (မြန်မာဘာသာ)', value: '缅甸语' },
  { text: '高棉语 (ភាសាខ្មែរ)', value: '高棉语' },
  { text: '老挝语 (ພາສາລາວ)', value: '老挝语' },
  { text: '尼泊尔语 (नेपाली)', value: '尼泊尔语' },
  { text: '僧伽罗语 (සිංහල)', value: '僧伽罗语' },
  { text: '马来语 (Bahasa Melayu)', value: '马来语' },
  { text: '塔加拉语 (Tagalog)', value: '塔加拉语' },
  { text: '哈萨克语 (Қазақша)', value: '哈萨克语' },
  { text: '乌兹别克语 (Oʻzbekcha)', value: '乌兹别克语' },
  { text: '阿塞拜疆语 (Azərbaycanca)', value: '阿塞拜疆语' },
  { text: '格鲁吉亚语 (ქართული)', value: '格鲁吉亚语' },
  { text: '亚美尼亚语 (Հայերեն)', value: '亚美尼亚语' },
  { text: '阿尔巴尼亚语 (Shqip)', value: '阿尔巴尼亚语' },
  { text: '斯洛伐克语 (Slovenčina)', value: '斯洛伐克语' },
  { text: '斯洛文尼亚语 (Slovenščina)', value: '斯洛文尼亚语' },
  { text: '立陶宛语 (Lietuvių)', value: '立陶宛语' },
  { text: '拉脱维亚语 (Latviešu)', value: '拉脱维亚语' },
  { text: '爱沙尼亚语 (Eesti)', value: '爱沙尼亚语' },
  { text: '冰岛语 (Íslenska)', value: '冰岛语' },
  { text: '爱尔兰语 (Gaeilge)', value: '爱尔兰语' },
  { text: '威尔士语 (Cymraeg)', value: '威尔士语' },
  { text: '苏格兰盖尔语 (Gàidhlig)', value: '苏格兰盖尔语' },
  { text: '巴斯克语 (Euskara)', value: '巴斯克语' },
  { text: '加泰罗尼亚语 (Català)', value: '加泰罗尼亚语' },
  { text: '加利西亚语 (Galego)', value: '加利西亚语' },

  // 其他语言
  { text: '毛利语 (Te Reo Māori)', value: '毛利语' },
  { text: '夏威夷语 (ʻŌlelo Hawaiʻi)', value: '夏威夷语' },
  { text: '因纽特语 (Inuktitut)', value: '因纽特语' },
  { text: '切罗基语 (ᏣᎳᎩ)', value: '切罗基语' },
  { text: '纳瓦霍语 (Diné Bizaad)', value: '纳瓦霍语' },
  { text: '藏语 (བོད་སྐད་)', value: '藏语' },
  { text: '维吾尔语 (ئۇيغۇرچە)', value: '维吾尔语' },
  { text: '蒙古语 (Монгол)', value: '蒙古语' },
  { text: '彝语 (ꆈꌠ꒿)', value: '彝语' },
  { text: '壮语 (Vahcuengh)', value: '壮语' },
  { text: '苗语 (Hmong)', value: '苗语' },
  { text: '白语 (Bai)', value: '白语' },
  { text: '布依语 (Buxqyaix)', value: '布依语' },
  { text: '傣语 (傣仂语)', value: '傣语' },
  { text: '黎语 (Hlai)', value: '黎语' },
  { text: '土家语 (Tujia)', value: '土家语' },
  { text: '满语 (ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ)', value: '满语' },
  { text: '锡伯语 (Sibe)', value: '锡伯语' },
  { text: '琉球语 (ウチナーグチ)', value: '琉球语' },
  { text: '阿伊努语 (アィヌ・イタㇰ)', value: '阿伊努语' },
  { text: '梵语 (संस्कृतम्)', value: '梵语' },
  { text: '巴利语 (Pāli)', value: '巴利语' },
  { text: '古英语 (Englisc)', value: '古英语' },
  { text: '中古汉语 (中古音)', value: '中古汉语' },
  { text: '拉丁语 (Latina)', value: '拉丁语' },
  { text: '古希腊语 (Ἀρχαία Ἑλληνική)', value: '古希腊语' },
  { text: '古典阿拉伯语 (العربية الفصحى)', value: '古典阿拉伯语' },
  { text: '教会斯拉夫语 (Церковнославя́нский)', value: '教会斯拉夫语' },
  { text: '世界语 (Esperanto)', value: '世界语' },
  { text: '克林贡语 (tlhIngan Hol)', value: '克林贡语' },
  { text: '多斯拉克语 (Dothraki)', value: '多斯拉克语' }
] 