name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Setup Linux build environment
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install core
          sudo snap install snapcraft --classic
          sudo snap install lxd
          sudo lxd init --auto
          sudo usermod -a -G lxd $USER
          mkdir -p snap/local
          chmod +x snap/local/desktop-launch

      - name: Setup macOS build environment
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p build
          security create-keychain -p dummy build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p dummy build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          rm -rf ~/.cache/electron-builder
          npm run build:linux
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p build
          npm run build:mac
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}